### ISSUE TITLE
media_comments not work properly

### ISSUE THREAD

**Issue by NovinDeveloper** [subzeroid/instagrapi#1247]
The function "media_comments" does not work properly and the number of comments that comes back is between 0 and 3, However, when reviewing the app or website, there are more comments.

**Comment by adw0rd** [comment]
Please provide an example code that reproduces the situation you specified

**Comment by NovinDeveloper** [comment]
`import instagrapi`

`username = 'username'`
`password = 'password'`
`cl = instagrapi.Client()`
`cl.login(username, password)`
`comments = cl.media_comments('3063629484317746449_173560420')`
# or
`comments = cl.media_comments('3062630471627405161_173560420')`

**example_data_file:**

[website_3062630471627405161_173560420.txt](https://github.com/adw0rd/instagrapi/files/11182579/website_3062630471627405161_173560420.txt)
[website_3063629484317746449_173560420.txt](https://github.com/adw0rd/instagrapi/files/11182580/website_3063629484317746449_173560420.txt)
[instagrapi_3062630471627405161_173560420.txt](https://github.com/adw0rd/instagrapi/files/11182581/instagrapi_3062630471627405161_173560420.txt)
[instagrapi_3063629484317746449_173560420.txt](https://github.com/adw0rd/instagrapi/files/11182582/instagrapi_3063629484317746449_173560420.txt)

**Comment by musaib821** [comment]
Are you able to run this package properly???

**Comment by PonyOny** [comment]
Having the same issue, when using cl.media_comments() wit the mediaId I always get empty result of 0 comments.
