### ISSUE TITLE
[help wanted] Is there any alternative way to check whether the session is valid or not.

### ISSUE THREAD

**Issue by PrantaChakraborty** [subzeroid/instagrapi#1578]
I'm using the `get_timeline_feed()` method to check whether the session is valid. But this code takes too much time. Also, other API calls are taking too much time though I'm using a paid proxy. For example to search user by username took almost 30-35 seconds.

**Comment by SaeidB** [comment]
getting timeline feed will take less than 5 sec to execute ,

so if it take 30 sec for u to run , i guess it relate to your proxy

**Comment by PrantaChakraborty** [comment]
@SaeidB can you suggest me some good proxies, please?

**Comment by SaeidB** [comment]
> @SaeidB can you suggest me some good proxies, please?

Most proxies will work without problem, just change your provider or send them ticket and ask for help.
