### ISSUE TITLE
[BUG] Response HTTP 503 and 504

### ISSUE THREAD

**Issue by yeuharn96** [subzeroid/instagrapi#1604]
Hello, I was trying to send GET request but server always response either HTTP 503 or 504 status code

```
request url: https://api.hikerapi.com/a1/user?username=ronaldo
header: { contentType: 'application/json', 'x-access-key': xxx }
```

Response when status code is 503:
```
{ "state": false, "error": "Service Unavailable" }
```

Response when status code is 504:
```
{"state":false,{"error":"timeout"}
```

**Comment by rickturner2001** [comment]
Are you trying to retreive data for a user by username? if so, judging from the [documentation](https://api.hikerapi.com/docs#/%2Fv1%2Fuser/user_by_username_v1_user_by_username_get) it seems like you're using the wrong url.

Just a friendly reminder that  this should not be here as it's part of the API used by Instagrapi, but not part of the library. Stackoverflow or Github discussions might be a better choice next time

**Comment by yeuharn96** [comment]
Yes, thanks for pointing out!
I was following this [documentation](https://hiker-doc.readthedocs.io/en/latest/gettingstarted.html#example-of-writing-into-a-file) actually, didn't know they have a different version.

Thanks for the reminder, I'll close this issue now.
