### ISSUE TITLE
[BUG] Can't login with username and pass

### ISSUE THREAD

**Issue by pkovalev-aim** [subzeroid/instagrapi#1627]
instagrapi.exceptions.BadPassword: The password you entered is incorrect. Please try again. If you are sure that the password is correct, then change your IP address, because it is added to the blacklist of the Instagram Server
![Screenshot from 2023-10-24 15-45-23](https://github.com/subzeroid/instagrapi/assets/92786955/e27aa571-796b-4a2c-b431-c98337c569a3)
![Screenshot from 2023-10-24 15-46-40](https://github.com/subzeroid/instagrapi/assets/92786955/692643c8-4b08-4a14-b8c6-5aadddc36035)
The username and password are exactly correct

But using login_by_sessionid I can get the data but can't upload the photo.
instagrapi.exceptions.LoginRequired: login_required

**Comment by pkovalev-aim** [comment]
If you enable IFA, there is no error, but instagram blocks that input as suspicious. Is there a solution to this?

**Comment by pkovalev-aim** [comment]
The addition of the MFA solved the first problem. The second problem also found a solution.

**Comment by andrey-germanov** [comment]
> The addition of the MFA solved the first problem. The second problem also found a solution.

may you tell me about the solution of the second problem?
