### ISSUE TITLE
{"__a": 1, "__d": "dis"} doesn't work anymore

### ISSUE THREAD

**Issue by nebula0225** [subzeroid/instagrapi#1709]
![image](https://github.com/subzeroid/instagrapi/assets/93500898/364d1ec8-7863-43bb-bf7f-07e26d562e25)

URL : https://www.instagram.com/explore/tags/work/?__a=1&__d=dis

instagram changed end point

**Comment by nebula0225** [comment]
I changed logic with graphql
and sloved that problem

**Comment by masonwrolstad** [comment]
> I changed logic with graphql and sloved that problem

@nebula0225 any example of how you solved this using GraphQL? I was also using this endpoint and it's been broken. Thanks for your help!
