### ISSUE TITLE
[BUG] external_url

### ISSUE THREAD

**Issue by Reloisback** [subzeroid/instagrapi#1732]
I tried different accounts and connections, but there is no change even though it says external URL has changed. Also, if there is 1 external_url in the profile, when I want to change it, it adds a 2nd external_url, that is, it does not edit or delete the old one.

`
from instagrapi import Client

USERNAME = 'username'
PASSWORD = 'pass'

cl = Client()
cl.login(USERNAME, PASSWORD)
account_info = cl.account_info().dict()
print(account_info)

cl.account_edit(external_url='https://URL')

`

**Comment by Reloisback** [comment]
cl.set_external_url(external_url='https://url/'') 
This worked and added a link, but now it is necessary to delete the old one if it exists.

**Comment by Reloisback** [comment]
I saw a code here in past issues like this and it works.

`
def delete_external_links(api):
    result = api.private_request("accounts/current_user/?edit=true")
    time.sleep(5)

    for link in result.get('user', {}).get('bio_links', []):
        print("DELETING LINK " + str(link))

        signed_body = f"signed_body=SIGNATURE.%7B%22_uid%22%3A%22{api.user_id}%22%2C%22_uuid%22%3A%22{api.uuid}%22%2C%22link_ids%22%3A%22%5B%5C%22{link.get('link_id', '')}%5C%22%5D%22%7D"

        response = api.private_request("accounts/remove_bio_links/", data=signed_body, with_signature=False)
        print(response)

        time.sleep(4) `
        
        Use;
        
        delete_external_links(cl)

**Comment by mxb3** [comment]
I tried this and it removes only 1 link not if i have more than one. Do you know what the code would be if i need to remove more?

**Comment by mxb3** [comment]
Solved by just re writing the code 2 times

**Comment by barutlift** [comment]
> cl.set_external_url(external_url='https://url/'') This worked and added a link, but now it is necessary to delete the old one if it exists.

su thanks man that worked
