### ISSUE TITLE
[BUG] Started getting 400 response from login

### ISSUE THREAD

**Issue by mirubinstein** [subzeroid/instagrapi#1739]
**Describe the bug**
As of today, I've started getting a 400 response from the following POST call:
[400] POST https://i.instagram.com/api/v1/accounts/login/ (269.0.0.18.75, OnePlus 6T Dev)

I'm seeing this for two separate accounts, neither of which have two-factor auth enabled. Any ideas?

**To Reproduce**
Attempt to log into Instagram using client.login method.

**Traceback**
Show your full traceback so that it is clear where exactly the error occurred.

[400] POST https://i.instagram.com/api/v1/accounts/login/ (269.0.0.18.75, OnePlus 6T Dev)
Status 400: Empty response message. Maybe enabled Two-factor auth?

**Expected behavior**
Expecting Instagram to log in properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 21.04] - Linus
 - Python version [e.g. 3.8.3] - 3.11.7
 - instagrapi version [e.g. 1.9.3, not "latest"] - Latest
 - moveipy version if used
 - imagemagick version if used

**Additional context**

**Comment by tajbowness** [comment]
What exception type was thrown?

**Comment by mirubinstein** [comment]
Looks like it's resolved now - maybe a transient issue from Instagram
