### ISSUE TITLE
[BUG] user agent cannot be modified to conform to configured terminal

### ISSUE THREAD

**Issue by Systemac** [subzeroid/instagrapi#1841]
### Try Instagrapi SaaS with a free trial https://hikerapi.com/p/5GBWznd3

**Describe the bug**
user agent cannot be modified to conform to configured terminal

**To Reproduce**
my code :

![image](https://github.com/subzeroid/instagrapi/assets/7353752/1deb3e57-c5d3-45f9-a3eb-881ae6856723)

and the session.json : 

![image](https://github.com/subzeroid/instagrapi/assets/7353752/fe25e680-1768-4450-97cf-8c823bf74165)

**Desktop (please complete the following information):**
 - OS: Docker
 - Python version 3.10.
 - instagrapi version 2.0.3
 - moveipy version if used
 - imagemagick version if used

I apologize if I haven't put the data in the right order, but the tutorial isn't very clear on this point, or at least there aren't any examples.

**Comment by tajbowness** [comment]
Perhaps try using the "os" and "json" modules to edit the JSON file.

**Comment by Systemac** [comment]
I've already tried it but it resets the basic settings, I don't understand my mistake...

**Comment by Systemac** [comment]
So stupid sorry, replace self.cl.set_user_agent = "" by self.cl.set_user_agent("")

**Comment by sujay1599** [comment]
Look into how I manage sessions - https://github.com/sujay1599/InstagramTheftyScraperPosterHuman
