### ISSUE TITLE
Need examples for StorySticker

### ISSUE THREAD

**Issue by Ch41r05** [subzeroid/instagrapi#1936]
Hello everyone,

Thanks for your wonderful effort in providing us an easy to use instagram api.
I'm finding some hardships when trying to post stories with a link sticker. Using the StoryLink class correctly makes the link available (when using height and width big enough to cover most of the story) but no sticker is being visualized.
I tried to apply other sticker with the StorySticker class, but nothing seems to work.
Looking in the documentation, I can't find a working example of StorySticker usage and the old links to using "Charles" are all expired, so I'm not sure what I should be doing. Would you please submit a working example so I can try and learn?

Thanks a lot

**Comment by Ch41r05** [comment]
Hello @itsManeka ,

Thanks for spending your time answering me! I understand that instagrapi doesn't have sticker images, what I was wondering about was how to process Instagram images so I can show them using instagrapi, since the guide doesn't have any examples and I have no idea on how to do it since I 'm new to this. Would it be possible to have this added to the guide? Or having some code snippet that lets me understand how to do that?

Thanks a lot

**Comment by Ch41r05** [comment]
@itsManeka thanks for the response, now I understand! What I'm wondering about now (maybe I'm missing something) is what are the StorySticker objects supposed to do since the sticker should only be merged into the base image. Thanks anyway for the explaination!

**Comment by itsManeka** [comment]
Your welcome!
I believe that stickers should have different classes due to their different functionalities (reactions, links, locations, etc.)
Most likely there are also properties with different names on the endpoints and, therefore, they should be separated.

If there are no more questions left, I believe the issue can be closed.

**Comment by Ch41r05** [comment]
Thanks! Yes, I'll close the issue
