### ISSUE TITLE
[feature request] broad cast channels

### ISSUE THREAD

**Issue by rockfly830** [subzeroid/instagrapi#1974]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
user_infos returns the broadcast channels infos as well.

**Describe alternatives you've considered**
All necessary information about broadcast channels is already returned by the Instagram API. It would only be necessary to create a new type and extract the information.

**Additional context**
On Instagram on mobile, some profiles (I don't know if only verified accounts can use this feature) have a private chat where only the creator can send messages. 

The Instagram profile calls this channel "What's Good on Instagram".

![Screenshot](https://github.com/user-attachments/assets/7ca47fb5-85d3-48ba-81f5-6f19e3e679ac)

**Comment by sunmasters** [comment]
Yes, Now a days popular accounts have this feature.

**Comment by honeyedoasis** [comment]
Hello, are there any docs on how to scrape the media / msgs within a broadcast channel?
I couldn't find any mention about how to use this feature. Thanks!

**Comment by rockfly830** [comment]
> Hello, are there any docs on how to scrape the media / msgs within a broadcast channel? I couldn't find any mention about how to use this feature. Thanks!

As far as I remember, broadcast channels work like direct, so you can use the already implemented methods.

**Comment by honeyedoasis** [comment]
Oh nice, I was able to query it by passing the `thread_igid` to `cl.direct_thread`. But doing this causes a crash.

```
extract_user_short, extractors.py:195
extract_direct_thread, extractors.py:288
direct_thread, direct.py:346
```

In `extract_direct_thread` it's tried to set the inviter like so:
```py
    if "inviter" in data:
        data["inviter"] = extract_user_short(data["inviter"])
```

When logging the json response, I see that the inviter is there but just set to null.
